name: Run nix flake update

on:
  schedule:
    - cron: "0 20 */3 * *"
  workflow_dispatch:

jobs:
  fetch-new-plugins:
    runs-on: ubuntu-latest
    name: run nix flake update
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Nix
        uses: cachix/install-nix-action@v18
      - run: |
         nix flake update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: github_action
          commit_user_email: ""
          commit_author: ""
          commit_message: 'update inputs'
          file_pattern: flake.lock
          # push_options: '--force'
